server:
  port: 80

eureka:
  client:
    # 表示是否将自己注入到EuerkaServer，默认true
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  # j建立连接所用时间，适用于网络状况正常的情况下，两端连接所用时间
  ReadTimeout: 5000
  # 建立连接后从服务器读取可用资源所用时间
  ConnectTimeout: 5000

  logging:
    level:
      com.atguigu.springcloud.service.PaymentFeignService: debug